name: Create Issue to Update Escrow Documentation
on:
  schedule:
    - cron: 5,10,15,20,26,28 * * *

jobs:
  create_issue:
    name: Update Escrow Documentation
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "zturchan"
          labels: "CompTracker.Web, Task"
          title: "Update Escrow Documentation"
          body: |
            Make sure the escrow docs are up to date with the latest workflows.
          pinned: false
          close-previous: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
