name: Create Issue to Update Escrow Documentation
on:
  schedule:
    - cron: 51,52,54,55,56,57,58,59,0,5,6,7,8,9,10,11,12,13,14,16,18,20,22,23,25,27 * * * *

jobs:
  create_issue:
    name: Update Escrow Documentation
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "zturchan"
          labels: "CompTracker.Web, Task"
          title: "Update Escrow Documentation"
          body: |
            Make sure the escrow docs are up to date with the latest workflows.
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
